name: "Build image and push to ECR"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ROLE_TO_ASSUME: "arn:aws:iam::179530787873:role/GitHubAction-AssumeRoleWithAction"
  AWS_REGION: "eu-west-1"
  ECR_REPOSITORY: "commute-train"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"
      - name: Build with Maven
        working-directory: ./backend
        run: mvn clean install

      # this step uses Github OIDC to assume the role in the sandbox account (the permissions section above is required for this to work)
      - name: Configure AWS credentials from Grad GP1 account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{env.ROLE_TO_ASSUME}}
          aws-region: ${{env.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: "latest"
        with:
          context: ./backend
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
